version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: appdb
    networks:
      - appnet
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "appdb"
    depends_on:
      - mongo
    networks:
      - appnet
    ports:
      - "8000:8000"

  flutter_web:
    build:
      context: ./flutter_app
      dockerfile: Dockerfile
    container_name: flutter_web
    depends_on:
      - backend
    networks:
      - appnet
    ports:
      - "8081:80"

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data: